server:
  port: 8080
spring:
  application:
    name: reggie-project #应用的名称，可选
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #数据库名称reggie
      url: jdbc:mysql://127.0.0.1:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root #你自己的数据库用户名，默认root
      password: yu123456 #你自己数据库的连接密码
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID #主键生成策略
reggie:
  path: E:\HaoCode\SSM\reggie\reggie-project\src\main\resources\backend\images\food\
